spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # 以uri作为前缀
          uri: http//localhost:8080/xxxx.git
          # 相对地址,uri下面的配置文件,后缀名称
          search-paths:
            - /user-service
            - /product-service
          username:
          password:


  profiles:
    active: $spring.profiles.active$


server:
  port: 8002
  context-path: /